import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    archive: [
        {
            type: 'autogenerated',
            dirName: 'archive',
        },
    ],
    tools: ['tools/jian-jie'],
    curated: [{ type: 'autogenerated', dirName: 'curated' }],
};

export default sidebars;
