import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    archive: [
        {
            type: 'autogenerated',
            dirName: 'archive',
        },
    ],
    tools: ['tools/简介'],
};

export default sidebars;
